// Generated by https://quicktype.io

export interface GetBestQualificated {
    id:          number;
    name:        string;
    description: string;
    category_id: number;
    createdAt:   string;
    updatedAt:   string;
    score:       Score;
    tags:        Category[];
    category:    Category;
    prices:      Price[];
    photos:      string[];
}

export interface Category {
    id:   number;
    name: string;
}

export interface Price {
    name:          string;
    logo:          string;
    id:            number;
    price:         number;
    shopProductId: number;
}

export interface Score {
    score:         number;
    califications: number;
}
