
export interface shopData{
    name: string,
    logo?: string
}

export interface CreateShopResponse {
    shop: Shop;
}

export interface Shop {
    id:        number;
    name:      string;
    user_id:   number;
    updatedAt: string;
    createdAt: string;
    logo:      string;
}
// Generated by https://quicktype.io

export interface GetShopResponse {
    id:        number;
    name:      string;
    logo:      string;
    user_id:   number;
    createdAt: string;
    updatedAt: string;
    products:  Product[];
}

export interface Product {
    id:          number;
    name:        string;
    description: string;
    category_id: number;
    createdAt:   string;
    updatedAt:   string;
    price:       number;
}

// Generated by https://quicktype.io

export interface GetAllShopsResponse {
    id:        number;
    name:      string;
    logo:      string;
    user_id:   number;
    createdAt: string;
    updatedAt: string;
}
export interface dataUpdateShop {
    name?: string
    logo?:string
}
