
export interface UserRegister {
    msg: string;
}

export interface dataUser{
    firstName:string;
    lastName: string;
    email:string;
    password:string;
    role:string;
    phone:string;
}

export interface authUser {
    email: string;
    password: string// Generated by https://quicktype.io
}

export interface LoginResponse {
    token: string;
    user:  User;
}

export interface User {
    id:           number;
    firstName:    string;
    lastName:     string;
    email:        string;
    password:     string;
    role:         string;
    phone:        string;
    profilePhoto: null;
    createdAt:    string;
    updatedAt:    string;
}

